# sepehr-sabz · tcp · SERVER (kernel socket wire spoof)
# rp_filter=0 روی eth0

[tunnel]
type      = "tcp"
mode      = "server"
local_ip  = "64.118.156.193"
remote_ip = "95.38.195.35"
cidr      = "10.99.0.0/24"
mtu       = 1400

[transport]
port               = 8443
proto              = "tcp"
heartbeat_interval = 10

[security]
encryption = false

[mangle]
srcip = "37.152.181.38"
dstip = "185.41.1.52"

[tuning]
enabled     = true
mode        = "resource"
sock_buf_mb = 32
tun_queues  = 1
tcp_streams = 2
poll_ms     = 10

[logging]
level = "info"

[health]
disabled = true
