# sepehr-sabz · udp · SERVER

[tunnel]
type      = "udp"
mode      = "server"
local_ip  = "64.118.156.193"
remote_ip = "95.38.195.35"
cidr      = "10.99.0.0/24"
mtu       = 1440

[transport]
port               = 5720
proto              = "udp"
heartbeat_interval = 10

[security]
encryption = false

[mangle]
srcip = "37.152.181.38"
dstip = "185.41.1.52"

[tuning]
enabled    = true
mode       = "balanced"
sock_buf_mb = 32
tun_queues  = 1
poll_ms     = 10

[logging]
level = "debug"

[health]
disabled = true
