# sepehr-sabz · gre-fou · CLIENT · 95.38.195.35
# sudo ./virlink -c client/gre-fou.toml

[tunnel]
type      = "gre-fou"
mode      = "client"
local_ip  = "95.38.195.35"
remote_ip = "64.118.156.193"
cidr      = "10.99.0.0/24"
mtu       = 1420

[transport]
port               = 5701
proto              = "fou"
heartbeat_interval = 10

[security]
encryption = false

[mangle]
srcip = "185.41.1.52"
dstip = "37.152.181.38"

[tuning]
enabled = true
mode    = "balanced"

[logging]
level            = "debug"
profile          = true
profile_interval = 30

[health]
disabled = true
