# sepehr-sabz · l2tpv3 · CLIENT

[tunnel]
type      = "l2tpv3"
mode      = "client"
local_ip  = "95.38.195.35"
remote_ip = "64.118.156.193"
cidr      = "10.99.0.0/24"
mtu       = 1464

[transport]
port  = 5705
proto = "l2tp"

[l2tp]
client_tunnel_id  = 1000
server_tunnel_id  = 2000
client_session_id = 1000
server_session_id = 2000

[security]
encryption = false

[mangle]
srcip = "185.41.1.52"
dstip = "37.152.181.38"

[tuning]
enabled = true
mode    = "balanced"

[logging]
level = "debug"

[health]
disabled = true
