// tun_icmp.go — ICMP Echo tunnel (IP protocol 1).
//
// Architecture:
//   [TUN device] ←→ [Go userspace] ←→ [raw ICMP socket]
//
// IP packets from TUN are wrapped in ICMP Echo Request frames and sent via
// a raw IPPROTO_ICMP socket. Both sides send Echo Requests (type 8) and
// only accept Echo Requests — Echo Replies (auto-generated by the kernel)
// are ignored.
//
// ICMP frame format:
//   [Type=8][Code=0][Checksum(2B)][ID=0xCAFE(2B)][Seq(2B)][inner IP packet]
//
// Filtering: type==8 AND id==0xCAFE — distinguishes tunnel traffic from
// normal ping traffic and kernel-generated auto-replies.
package main

import (
	"encoding/binary"
	"fmt"
	"net"
	"os"
	"sync/atomic"

	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

const (
	icmpSubnet  = "10.20.43.0/24"
	icmpTunID   = uint16(0xCAFE) // magic ID to identify tunnel ICMP packets
	icmpEchoReq = 8              // ICMP Echo Request type
)

// IcmpTunnel encapsulates IP traffic in ICMP Echo Request messages.
// Requires CAP_NET_RAW (root).
type IcmpTunnel struct {
	cfg     *Config
	tunFd   *os.File
	rawFd   int // raw IPPROTO_ICMP socket
	done    chan struct{}
	seq     atomic.Uint32
	lastSrc atomic.Value // [4]byte — server tracks client IP
}

func (t *IcmpTunnel) DevName() string   { return "icmp-tun0" }
func (t *IcmpTunnel) OverlayIP() string { return overlayAddr(t.cfg, icmpSubnet) }
func (t *IcmpTunnel) PeerIP() string    { return peerAddr(t.cfg, icmpSubnet) }

func (t *IcmpTunnel) Up() error {
	c := t.cfg
	dev := t.DevName()
	addr := t.OverlayIP()
	peer := t.PeerIP()
	mtu := c.Tunnel.MTU
	if mtu == 0 {
		mtu = 1472 // 1500 − 20 (IP) − 8 (ICMP header)
	}

	header("icmp / " + c.Mode)
	step("sysctl (via /proc/sys)...")
	applySysctl()
	step("cleanup...")
	t.doClean()

	// ── TUN device ────────────────────────────────────────────────────────────
	step(fmt.Sprintf("TUN device %s...", dev))
	var err error
	t.tunFd, err = openTunDev(dev)
	if err != nil {
		return fmt.Errorf("tun: %w", err)
	}
	l, err := netlink.LinkByName(dev)
	if err != nil {
		return fmt.Errorf("link %s: %w", dev, err)
	}
	netlink.LinkSetMTU(l, mtu)
	a, _ := netlink.ParseAddr(addr)
	netlink.AddrAdd(l, a)
	netlink.LinkSetUp(l)
	logOK(fmt.Sprintf("%s  %s  MTU=%d", dev, addr, mtu))

	// ── raw ICMP socket ───────────────────────────────────────────────────────
	step("raw ICMP socket (protocol 1)...")
	t.rawFd, err = unix.Socket(unix.AF_INET, unix.SOCK_RAW, unix.IPPROTO_ICMP)
	if err != nil {
		return fmt.Errorf("SOCK_RAW IPPROTO_ICMP: %w", err)
	}
	// 1-second receive timeout so the goroutine can check done periodically
	tv := unix.Timeval{Sec: 1, Usec: 0}
	unix.SetsockoptTimeval(t.rawFd, unix.SOL_SOCKET, unix.SO_RCVTIMEO, &tv)
	logOK("raw ICMP socket ready")

	addMSS(dev)
	t.done = make(chan struct{})

	// client knows the fixed destination; server dynamically tracks source
	var fixedDst [4]byte
	if c.Mode == "client" {
		ip := net.ParseIP(c.RemoteIP).To4()
		copy(fixedDst[:], ip)
	}

	go t.rxLoop(fixedDst)
	go t.txLoop(fixedDst)

	done(dev, addr, peer,
		"proto    : ICMP Echo (IP protocol 1, type=8 both directions)",
		"id       : 0xCAFE  (tunnel marker)",
		"firewall : allow ICMP between both servers",
		"test     : ping -c3 "+peer,
	)
	return nil
}

// rxLoop: raw ICMP socket → TUN
func (t *IcmpTunnel) rxLoop(fixedDst [4]byte) {
	// IP header (20B) + ICMP header (8B) + payload
	buf := make([]byte, 1500+28)
	for {
		n, from, err := unix.Recvfrom(t.rawFd, buf, 0)
		if err != nil {
			select {
			case <-t.done:
				return
			default:
				// EAGAIN = timeout, retry; EBADF = socket closed
				if err == unix.EAGAIN || err == unix.EWOULDBLOCK || err == unix.EBADF {
					continue
				}
				logWarn("icmp rx: " + err.Error())
				continue
			}
		}

		// strip IPv4 header
		if n < 20 {
			continue
		}
		ihl := int(buf[0]&0xf) * 4
		if n < ihl+8 {
			continue
		}
		icmp := buf[ihl:n]

		// filter: only ICMP Echo Request (type 8) with our tunnel ID
		if icmp[0] != icmpEchoReq {
			continue
		}
		id := binary.BigEndian.Uint16(icmp[4:6])
		if id != icmpTunID {
			continue
		}

		// server: learn client's IP for the tx direction
		if t.cfg.Mode == "server" {
			if sa, ok := from.(*unix.SockaddrInet4); ok {
				t.lastSrc.Store(sa.Addr)
			}
		} else {
			// client: filter for packets from our fixed server only
			if sa, ok := from.(*unix.SockaddrInet4); ok && sa.Addr != fixedDst {
				continue
			}
		}

		payload := icmp[8:] // skip ICMP header
		if _, err := t.tunFd.Write(payload); err != nil {
			select {
			case <-t.done:
				return
			default:
				logWarn("tun write: " + err.Error())
			}
		}
	}
}

// txLoop: TUN → raw ICMP socket
func (t *IcmpTunnel) txLoop(fixedDst [4]byte) {
	buf := make([]byte, 65536)
	for {
		n, err := t.tunFd.Read(buf)
		if err != nil {
			select {
			case <-t.done:
				return
			default:
				logWarn("tun read: " + err.Error())
				continue
			}
		}

		// determine destination
		var dst [4]byte
		if t.cfg.Mode == "client" {
			dst = fixedDst
		} else {
			if v := t.lastSrc.Load(); v != nil {
				dst = v.([4]byte)
			} else {
				continue // server has not seen a client yet
			}
		}

		seq := uint16(t.seq.Add(1))
		frame := buildICMPEcho(icmpTunID, seq, buf[:n])
		sa := &unix.SockaddrInet4{Addr: dst}
		if err := unix.Sendto(t.rawFd, frame, 0, sa); err != nil {
			logDebug("icmp tx: " + err.Error())
		}
	}
}

// buildICMPEcho constructs an ICMP Echo Request packet with checksum.
func buildICMPEcho(id, seq uint16, payload []byte) []byte {
	pkt := make([]byte, 8+len(payload))
	pkt[0] = icmpEchoReq // Type: Echo Request
	pkt[1] = 0           // Code
	// pkt[2:4] = checksum (zero for now)
	binary.BigEndian.PutUint16(pkt[4:], id)
	binary.BigEndian.PutUint16(pkt[6:], seq)
	copy(pkt[8:], payload)
	cs := icmpChecksum(pkt)
	binary.BigEndian.PutUint16(pkt[2:], cs)
	return pkt
}

// icmpChecksum computes the 16-bit ones-complement checksum.
func icmpChecksum(b []byte) uint16 {
	var sum uint32
	for i := 0; i+1 < len(b); i += 2 {
		sum += uint32(b[i])<<8 | uint32(b[i+1])
	}
	if len(b)&1 != 0 {
		sum += uint32(b[len(b)-1]) << 8
	}
	for sum > 0xffff {
		sum = (sum >> 16) + (sum & 0xffff)
	}
	return ^uint16(sum)
}

func (t *IcmpTunnel) Down() error {
	t.doClean()
	logOK("icmp tunnel torn down")
	return nil
}

func (t *IcmpTunnel) doClean() {
	if t.done != nil {
		select {
		case <-t.done:
		default:
			close(t.done)
		}
		t.done = nil
	}
	if t.rawFd != 0 {
		unix.Close(t.rawFd)
		t.rawFd = 0
	}
	if t.tunFd != nil {
		t.tunFd.Close()
		t.tunFd = nil
	}
	delMSS(t.DevName())
	nlDown(t.DevName())
}

func (t *IcmpTunnel) Status() {
	if l, err := netlink.LinkByName(t.DevName()); err == nil {
		fmt.Printf("  %s: flags=%v\n", l.Attrs().Name, l.Attrs().Flags)
	}
}
