# spooftest · vxlan-wg · CLIENT
# ۱) ./virlink keygen   ۲) کلیدها را جایگزین کن

[tunnel]
type      = "vxlan-wg"
mode      = "client"
local_ip  = "95.38.195.51"
remote_ip = "37.221.93.111"
cidr      = "10.99.0.0/24"
mtu       = 1360

[transport]
port  = 5711
proto = "wireguard"

[wireguard]
client_private_key = "REPLACE_CLIENT_PRIVATE_KEY"
client_public_key  = "REPLACE_CLIENT_PUBLIC_KEY"
server_private_key = "REPLACE_SERVER_PRIVATE_KEY"
server_public_key  = "REPLACE_SERVER_PUBLIC_KEY"
vni                = 99

[security]
encryption = true

[mangle]
srcip = "185.217.6.110"
dstip = "37.152.181.38"

[tuning]
enabled = true
mode    = "balanced"

[logging]
level = "debug"

[health]
disabled = true
